version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  commands:
    - sphinx-build -b html docs docs/_build/html

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

