version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .  # This will install your package
    - requirements: requirements.txt  # If you have a main requirements file
    - method: pip
      path: .
      extra_requirements:
        - docs  # If you have docs extra in your setup.py/pyproject.toml
    - method: pip
      path: null
      extra_requirements: null
      requirements: null
      packages:
        - sphinx  # Explicitly install Sphinx
        - sphinx_rtd_theme  # Common theme, add if needed

