version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  commands:
    - sphinx-apidoc -o docs pioneer
    - sphinx-build -b html docs docs/_build/html

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
