version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"


python:
  install:
    - method: pip
      path: .
    - method: pip
      path: null
      requirements: null
      packages:
        - sphinx
        - sphinx-rtd-theme

sphinx:
  configuration: docs/conf.py
